"""add_readiness_reports

Revision ID: 2782f156b3f1
Revises: 9727e14e95b5
Create Date: 2026-04-25 13:08:08.166980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2782f156b3f1'
down_revision: Union[str, Sequence[str], None] = '9727e14e95b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readiness_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=False),
    sa.Column('readiness_label', sa.String(), nullable=False),
    sa.Column('training_gate', sa.String(), nullable=False),
    sa.Column('report_json', sa.String(), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_date', name='uq_readiness_user_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readiness_reports')
    # ### end Alembic commands ###
