"""initial schema

Revision ID: 6b898e6c283a
Revises: 
Create Date: 2026-04-24 17:12:55.089186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b898e6c283a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('active_calories', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('avg_resting_hr', sa.Integer(), nullable=True),
    sa.Column('hrv_last_night_ms', sa.Float(), nullable=True),
    sa.Column('vo2max', sa.Float(), nullable=True),
    sa.Column('acute_load', sa.Float(), nullable=True),
    sa.Column('chronic_load', sa.Float(), nullable=True),
    sa.Column('acwr', sa.Float(), nullable=True),
    sa.Column('body_battery_min', sa.Integer(), nullable=True),
    sa.Column('body_battery_max', sa.Integer(), nullable=True),
    sa.Column('sleep_score', sa.Integer(), nullable=True),
    sa.Column('sleep_duration_min', sa.Integer(), nullable=True),
    sa.Column('deep_sleep_min', sa.Integer(), nullable=True),
    sa.Column('rem_sleep_min', sa.Integer(), nullable=True),
    sa.Column('stress_avg', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('workouts_json', sa.String(), nullable=True),
    sa.Column('raw_garmin_json', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'source', name='uq_daily_metrics_user_date_source')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('goal_event', sa.String(), nullable=True),
    sa.Column('goal_date', sa.Date(), nullable=True),
    sa.Column('fitness_level', sa.String(), nullable=True),
    sa.Column('medical_conditions', sa.String(), nullable=True),
    sa.Column('dietary_preference', sa.String(), nullable=True),
    sa.Column('dietary_allergies', sa.String(), nullable=True),
    sa.Column('max_weekly_hours', sa.Float(), nullable=True),
    sa.Column('garmin_email', sa.String(), nullable=True),
    sa.Column('garmin_password', sa.String(), nullable=True),
    sa.Column('model_analysis', sa.String(), nullable=False),
    sa.Column('model_planning', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('avg_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('tss', sa.Float(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('garmin_activity_id', sa.String(), nullable=True),
    sa.Column('raw_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feedback_date', sa.Date(), nullable=False),
    sa.Column('workout_id', sa.String(), nullable=True),
    sa.Column('free_text', sa.String(), nullable=True),
    sa.Column('perceived_effort', sa.Integer(), nullable=True),
    sa.Column('mood', sa.Integer(), nullable=True),
    sa.Column('override_choice', sa.String(), nullable=True),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.drop_table('workouts')
    op.drop_table('user_profiles')
    op.drop_table('jobs')
    op.drop_table('daily_metrics')
    op.drop_table('users')
    # ### end Alembic commands ###
